version: '2'
services:
    cafeapp-app:
        image: cafeapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cafeapp-mysql:3306/cafeapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cafeapp-elasticsearch:9300
        ports:
            - 8080:8080
    cafeapp-mysql:
        extends:
            file: mysql.yml
            service: cafeapp-mysql
    cafeapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cafeapp-elasticsearch
